### ISSUE TITLE
Can't select title/message fonts

### ISSUE THREAD

**Issue by godexsoft** [JanGorman/SwiftMessageBar#18]
Nice little library but does not allow me to select the fonts to use. Please fix? Thanks

**Comment by JanGorman** [comment]
Thanks for the suggestion. 4.1.0 adds support for this via the `MessageBarConfig`. There's a new `Builder` for easy configuration. I've updated the README with an example.

**Comment by godexsoft** [comment]
Awesome, thanks. I noticed it when i updated all my pods last night but that was after i posted this issue :) thanks again
