### ISSUE TITLE
show message in rtl language

### ISSUE THREAD

**Issue by alishojaeiir** [JanGorman/SwiftMessageBar#29]
how can i show message in rtl language

**Comment by JanGorman** [comment]
Hi – if you're using it in a device set to RTL it should naturally follow what is set in the system. See the attached screenshot of what it looks like when you set the simulator to RTL pseudo language.
You can force RTL and override the system by passing the parameter `languageDirection = .rightToLeft`

![Screenshot 2019-04-15 at 09 44 01](https://user-images.githubusercontent.com/138166/56115236-3fe6c480-5f63-11e9-918f-da7cf5e7251d.png)
