### ISSUE TITLE
Message with long text is cropped

### ISSUE THREAD

**Issue by nilshott** [JanGorman/SwiftMessageBar#5]
![long](https://cloud.githubusercontent.com/assets/289627/9305793/67b06512-44f4-11e5-9f36-1af4f7958378.png)

**Comment by JanGorman** [comment]
I've begun upgrading this to use Autolayout which I fixes the problem. Not without issues yet but hope to release into the wild early next week:

![screen shot 2015-08-19 at 22 03 59](https://cloud.githubusercontent.com/assets/138166/9367551/4e31e45a-46be-11e5-96c1-419dad501def.png)

![screen shot 2015-08-19 at 22 05 37](https://cloud.githubusercontent.com/assets/138166/9367573/7317f692-46be-11e5-8ca2-2d8d583ee356.png)
